# Generated by Django 5.0.1 on 2024-02-20 06:12

import five.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', five.models.UserManager()),
            ],
        ),
    ]
