# Generated by Django 5.0.1 on 2024-03-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role_name',
            field=models.CharField(choices=[('USER', 'User'), ('SURGEON', 'Surgeon'), ('RADIOLOGIST', 'Radiologist'), ('TELERADIOLOGIST', 'Teleradiologist')], db_column='role_name', default='USER', max_length=20),
        ),
    ]
